name: Main pipeline
on: [push]
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        java: [1.8, 9.0.x, 10, 11.0.x, 12, 13, 14, 15, 16, 17, 18]
    runs-on: ubuntu-latest
    name: Test full test suite on JDK ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Install G++7
      run: sudo apt install g++-7
    - name: Change to G++7
      run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - name: Build with Gradle
      run: ./gradlew build
      env:
        CC: gcc-7
        CXX: g++-7
